name: Tag Version

on:
  workflow_dispatch:
  push:
    branches:
      - test-tag-version-workflow

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for tagging, ensures full git history

      - name: Read version
        id: get_version
        run: |
          VERSION=$(jq -r '.version' version.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag v${{ steps.get_version.outputs.version }}
          git push origin v${{ steps.get_version.outputs.version }}